# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryStub(object):
    """=======================
    Service Definition
    =======================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBook = channel.unary_unary(
                '/library.Library/CreateBook',
                request_serializer=library__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=library__pb2.CreateBookResponse.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/library.Library/ListBooks',
                request_serializer=library__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=library__pb2.ListBooksResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/library.Library/UpdateBook',
                request_serializer=library__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=library__pb2.UpdateBookResponse.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/library.Library/DeleteBook',
                request_serializer=library__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=library__pb2.DeleteBookResponse.FromString,
                _registered_method=True)
        self.CreateMember = channel.unary_unary(
                '/library.Library/CreateMember',
                request_serializer=library__pb2.CreateMemberRequest.SerializeToString,
                response_deserializer=library__pb2.CreateMemberResponse.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/library.Library/ListMembers',
                request_serializer=library__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=library__pb2.ListMembersResponse.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/library.Library/UpdateMember',
                request_serializer=library__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=library__pb2.UpdateMemberResponse.FromString,
                _registered_method=True)
        self.DeleteMember = channel.unary_unary(
                '/library.Library/DeleteMember',
                request_serializer=library__pb2.DeleteMemberRequest.SerializeToString,
                response_deserializer=library__pb2.DeleteMemberResponse.FromString,
                _registered_method=True)
        self.BorrowBook = channel.unary_unary(
                '/library.Library/BorrowBook',
                request_serializer=library__pb2.BorrowRequest.SerializeToString,
                response_deserializer=library__pb2.BorrowResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/library.Library/ReturnBook',
                request_serializer=library__pb2.ReturnRequest.SerializeToString,
                response_deserializer=library__pb2.ReturnResponse.FromString,
                _registered_method=True)
        self.ListLoansForMember = channel.unary_unary(
                '/library.Library/ListLoansForMember',
                request_serializer=library__pb2.ListLoansForMemberRequest.SerializeToString,
                response_deserializer=library__pb2.ListLoansForMemberResponse.FromString,
                _registered_method=True)
        self.ListAllLoans = channel.unary_unary(
                '/library.Library/ListAllLoans',
                request_serializer=library__pb2.ListAllLoansRequest.SerializeToString,
                response_deserializer=library__pb2.ListAllLoansResponse.FromString,
                _registered_method=True)


class LibraryServicer(object):
    """=======================
    Service Definition
    =======================

    """

    def CreateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLoansForMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllLoans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=library__pb2.CreateBookRequest.FromString,
                    response_serializer=library__pb2.CreateBookResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=library__pb2.ListBooksRequest.FromString,
                    response_serializer=library__pb2.ListBooksResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=library__pb2.UpdateBookRequest.FromString,
                    response_serializer=library__pb2.UpdateBookResponse.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=library__pb2.DeleteBookRequest.FromString,
                    response_serializer=library__pb2.DeleteBookResponse.SerializeToString,
            ),
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=library__pb2.CreateMemberRequest.FromString,
                    response_serializer=library__pb2.CreateMemberResponse.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=library__pb2.ListMembersRequest.FromString,
                    response_serializer=library__pb2.ListMembersResponse.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=library__pb2.UpdateMemberRequest.FromString,
                    response_serializer=library__pb2.UpdateMemberResponse.SerializeToString,
            ),
            'DeleteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMember,
                    request_deserializer=library__pb2.DeleteMemberRequest.FromString,
                    response_serializer=library__pb2.DeleteMemberResponse.SerializeToString,
            ),
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=library__pb2.BorrowRequest.FromString,
                    response_serializer=library__pb2.BorrowResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=library__pb2.ReturnRequest.FromString,
                    response_serializer=library__pb2.ReturnResponse.SerializeToString,
            ),
            'ListLoansForMember': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLoansForMember,
                    request_deserializer=library__pb2.ListLoansForMemberRequest.FromString,
                    response_serializer=library__pb2.ListLoansForMemberResponse.SerializeToString,
            ),
            'ListAllLoans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllLoans,
                    request_deserializer=library__pb2.ListAllLoansRequest.FromString,
                    response_serializer=library__pb2.ListAllLoansResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.Library', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.Library', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Library(object):
    """=======================
    Service Definition
    =======================

    """

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/CreateBook',
            library__pb2.CreateBookRequest.SerializeToString,
            library__pb2.CreateBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/ListBooks',
            library__pb2.ListBooksRequest.SerializeToString,
            library__pb2.ListBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/UpdateBook',
            library__pb2.UpdateBookRequest.SerializeToString,
            library__pb2.UpdateBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/DeleteBook',
            library__pb2.DeleteBookRequest.SerializeToString,
            library__pb2.DeleteBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/CreateMember',
            library__pb2.CreateMemberRequest.SerializeToString,
            library__pb2.CreateMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/ListMembers',
            library__pb2.ListMembersRequest.SerializeToString,
            library__pb2.ListMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/UpdateMember',
            library__pb2.UpdateMemberRequest.SerializeToString,
            library__pb2.UpdateMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/DeleteMember',
            library__pb2.DeleteMemberRequest.SerializeToString,
            library__pb2.DeleteMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/BorrowBook',
            library__pb2.BorrowRequest.SerializeToString,
            library__pb2.BorrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/ReturnBook',
            library__pb2.ReturnRequest.SerializeToString,
            library__pb2.ReturnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLoansForMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/ListLoansForMember',
            library__pb2.ListLoansForMemberRequest.SerializeToString,
            library__pb2.ListLoansForMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllLoans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.Library/ListAllLoans',
            library__pb2.ListAllLoansRequest.SerializeToString,
            library__pb2.ListAllLoansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
